# Generated by Django 4.2.2 on 2023-07-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comments_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='summary',
            field=models.TextField(max_length=300, verbose_name='Текст комментария'),
        ),
    ]
