# Generated by Django 4.2.2 on 2023-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publications_options_alter_publications_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='photo',
            field=models.ImageField(upload_to='publications', verbose_name='Фото'),
        ),
    ]
