# Generated by Django 4.2.2 on 2023-07-28 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publications', '0003_alter_publications_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publications',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='publications',
            name='photo',
            field=models.ImageField(upload_to='publications', verbose_name='Фото публикации'),
        ),
    ]
